# Generated by Django 2.2 on 2020-06-23 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instruction_id', models.IntegerField()),
                ('case_ref_no', models.CharField(blank=True, max_length=100)),
                ('client_name', models.CharField(blank=True, max_length=100)),
                ('candidate_name', models.CharField(blank=True, max_length=100)),
                ('complete_address', models.CharField(blank=True, max_length=100)),
                ('period_of_stay', models.DateField()),
            ],
        ),
    ]
